"""
Multi-Class Urgency Mapping for All Diseases
Evidence-based urgency levels (1-5) for 527 diseases

Urgency Levels:
    5 - Critical: Immediate life threat, intervention within minutes
    4 - Emergent: Serious condition, intervention within hours  
    3 - Urgent: Needs attention within 24 hours
    2 - Standard: Needs attention within 2-3 days
    1 - Elective: Can be scheduled/chronic management
"""

# Dictionary mapping disease names (lowercase) to urgency level and golden hour minutes
URGENCY_MAPPING = {
    # ============================================================
    # LEVEL 5 - CRITICAL (Immediate, minutes)
    # ============================================================
    'cardiac arrest': {'urgency': 5, 'golden_hour': 4},
    'stroke': {'urgency': 5, 'golden_hour': 270},
    'sepsis': {'urgency': 5, 'golden_hour': 60},
    'pulmonary embolism': {'urgency': 5, 'golden_hour': 60},
    'pneumothorax': {'urgency': 5, 'golden_hour': 30},
    'acute respiratory distress syndrome (ards)': {'urgency': 5, 'golden_hour': 60},
    'intracerebral hemorrhage': {'urgency': 5, 'golden_hour': 60},
    'subarachnoid hemorrhage': {'urgency': 5, 'golden_hour': 60},
    'intracranial hemorrhage': {'urgency': 5, 'golden_hour': 60},
    'subdural hemorrhage': {'urgency': 5, 'golden_hour': 60},
    'gastrointestinal hemorrhage': {'urgency': 5, 'golden_hour': 60},
    'ectopic pregnancy': {'urgency': 5, 'golden_hour': 30},
    'cardiac arrest': {'urgency': 5, 'golden_hour': 4},
    'malignant hypertension': {'urgency': 5, 'golden_hour': 60},
    'cerebral edema': {'urgency': 5, 'golden_hour': 60},
    'anaphylaxis': {'urgency': 5, 'golden_hour': 10},
    'status epilepticus': {'urgency': 5, 'golden_hour': 5},
    'tension pneumothorax': {'urgency': 5, 'golden_hour': 10},
    'ischemia of the bowel': {'urgency': 5, 'golden_hour': 60},
    'peritonitis': {'urgency': 5, 'golden_hour': 60},
    'testicular torsion': {'urgency': 5, 'golden_hour': 360},
    'ovarian torsion': {'urgency': 5, 'golden_hour': 360},
    'acute kidney injury': {'urgency': 5, 'golden_hour': 120},
    'encephalitis': {'urgency': 5, 'golden_hour': 60},
    'endocarditis': {'urgency': 5, 'golden_hour': 120},
    'carbon monoxide poisoning': {'urgency': 5, 'golden_hour': 60},
    'poisoning due to gas': {'urgency': 5, 'golden_hour': 60},
    'drug poisoning due to medication': {'urgency': 5, 'golden_hour': 60},
    'poisoning due to sedatives': {'urgency': 5, 'golden_hour': 60},
    'poisoning due to analgesics': {'urgency': 5, 'golden_hour': 60},
    'poisoning due to antimicrobial drugs': {'urgency': 5, 'golden_hour': 60},
    'crushing injury': {'urgency': 5, 'golden_hour': 60},
    'injury to internal organ': {'urgency': 5, 'golden_hour': 60},
    'fracture of the skull': {'urgency': 5, 'golden_hour': 60},
    'injury to the abdomen': {'urgency': 5, 'golden_hour': 60},
    'head injury': {'urgency': 5, 'golden_hour': 60},
    'guillain barre syndrome': {'urgency': 5, 'golden_hour': 120},
    'ascending cholangitis': {'urgency': 5, 'golden_hour': 120},
    
    # ============================================================
    # LEVEL 4 - EMERGENT (Hours)
    # ============================================================
    'heart attack': {'urgency': 4, 'golden_hour': 90},
    'heart failure': {'urgency': 4, 'golden_hour': 240},
    'appendicitis': {'urgency': 4, 'golden_hour': 1440},
    'acute pancreatitis': {'urgency': 4, 'golden_hour': 360},
    'meningitis': {'urgency': 4, 'golden_hour': 60},
    'diabetic ketoacidosis': {'urgency': 4, 'golden_hour': 120},
    'acute glaucoma': {'urgency': 4, 'golden_hour': 120},
    'transient ischemic attack': {'urgency': 4, 'golden_hour': 60},
    'deep vein thrombosis (dvt)': {'urgency': 4, 'golden_hour': 240},
    'kidney failure': {'urgency': 4, 'golden_hour': 240},
    'acute bronchospasm': {'urgency': 4, 'golden_hour': 30},
    'asthma': {'urgency': 4, 'golden_hour': 30},
    'cholecystitis': {'urgency': 4, 'golden_hour': 360},
    'pyelonephritis': {'urgency': 4, 'golden_hour': 240},
    'pneumonia': {'urgency': 4, 'golden_hour': 480},
    'sickle cell crisis': {'urgency': 4, 'golden_hour': 120},
    'hyperkalemia': {'urgency': 4, 'golden_hour': 60},
    'hypokalemia': {'urgency': 4, 'golden_hour': 120},
    'hypernatremia': {'urgency': 4, 'golden_hour': 120},
    'hyponatremia': {'urgency': 4, 'golden_hour': 120},
    'hypoglycemia': {'urgency': 4, 'golden_hour': 30},
    'hypovolemia': {'urgency': 4, 'golden_hour': 60},
    'fluid overload': {'urgency': 4, 'golden_hour': 120},
    'atrial fibrillation': {'urgency': 4, 'golden_hour': 240},
    'atrial flutter': {'urgency': 4, 'golden_hour': 240},
    'paroxysmal ventricular tachycardia': {'urgency': 4, 'golden_hour': 60},
    'paroxysmal supraventricular tachycardia': {'urgency': 4, 'golden_hour': 120},
    'sick sinus syndrome': {'urgency': 4, 'golden_hour': 240},
    'heart block': {'urgency': 4, 'golden_hour': 120},
    'cardiomyopathy': {'urgency': 4, 'golden_hour': 360},
    'pericarditis': {'urgency': 4, 'golden_hour': 360},
    'intestinal obstruction': {'urgency': 4, 'golden_hour': 360},
    'ileus': {'urgency': 4, 'golden_hour': 360},
    'choledocholithiasis': {'urgency': 4, 'golden_hour': 360},
    'retinal detachment': {'urgency': 4, 'golden_hour': 240},
    'orbital cellulitis': {'urgency': 4, 'golden_hour': 240},
    'endophthalmitis': {'urgency': 4, 'golden_hour': 120},
    'central retinal artery or vein occlusion': {'urgency': 4, 'golden_hour': 60},
    'peritonsillar abscess': {'urgency': 4, 'golden_hour': 360},
    'abscess of the pharynx': {'urgency': 4, 'golden_hour': 360},
    'foreign body in the throat': {'urgency': 4, 'golden_hour': 60},
    'foreign body in the gastrointestinal tract': {'urgency': 4, 'golden_hour': 240},
    'foreign body in the eye': {'urgency': 4, 'golden_hour': 120},
    'pleural effusion': {'urgency': 4, 'golden_hour': 360},
    'pulmonary congestion': {'urgency': 4, 'golden_hour': 240},
    'atelectasis': {'urgency': 4, 'golden_hour': 360},
    'pulmonary hypertension': {'urgency': 4, 'golden_hour': 480},
    'preeclampsia': {'urgency': 4, 'golden_hour': 240},
    'hypertension of pregnancy': {'urgency': 4, 'golden_hour': 240},
    'uterine atony': {'urgency': 4, 'golden_hour': 30},
    'hydatidiform mole': {'urgency': 4, 'golden_hour': 480},
    'septic arthritis': {'urgency': 4, 'golden_hour': 240},
    'osteomyelitis': {'urgency': 4, 'golden_hour': 480},
    'delirium': {'urgency': 4, 'golden_hour': 240},
    'alcohol withdrawal': {'urgency': 4, 'golden_hour': 120},
    'drug withdrawal': {'urgency': 4, 'golden_hour': 120},
    'alcohol intoxication': {'urgency': 4, 'golden_hour': 240},
    'thrombocytopenia': {'urgency': 4, 'golden_hour': 360},
    'coagulation (bleeding) disorder': {'urgency': 4, 'golden_hour': 240},
    'aplastic anemia': {'urgency': 4, 'golden_hour': 480},
    'peripheral arterial embolism': {'urgency': 4, 'golden_hour': 360},
    'thoracic aortic aneurysm': {'urgency': 4, 'golden_hour': 360},
    'abdominal aortic aneurysm': {'urgency': 4, 'golden_hour': 360},
    'burn': {'urgency': 4, 'golden_hour': 120},
    'concussion': {'urgency': 4, 'golden_hour': 240},
    'fracture of the vertebra': {'urgency': 4, 'golden_hour': 240},
    'fracture of the pelvis': {'urgency': 4, 'golden_hour': 240},
    'dislocation of the shoulder': {'urgency': 4, 'golden_hour': 240},
    'dislocation of the elbow': {'urgency': 4, 'golden_hour': 240},
    
    # ============================================================
    # LEVEL 3 - URGENT (24 hours)
    # ============================================================
    'kidney stone': {'urgency': 3, 'golden_hour': 1440},
    'gallstone': {'urgency': 3, 'golden_hour': 1440},
    'diverticulitis': {'urgency': 3, 'golden_hour': 1440},
    'croup': {'urgency': 3, 'golden_hour': 480},
    'acute bronchitis': {'urgency': 3, 'golden_hour': 1440},
    'acute bronchiolitis': {'urgency': 3, 'golden_hour': 720},
    'acute sinusitis': {'urgency': 3, 'golden_hour': 1440},
    'acute otitis media': {'urgency': 3, 'golden_hour': 1440},
    'tracheitis': {'urgency': 3, 'golden_hour': 720},
    'mastoiditis': {'urgency': 3, 'golden_hour': 720},
    'cornea infection': {'urgency': 3, 'golden_hour': 720},
    'corneal abrasion': {'urgency': 3, 'golden_hour': 720},
    'iridocyclitis': {'urgency': 3, 'golden_hour': 720},
    'urinary tract infection': {'urgency': 3, 'golden_hour': 1440},
    'cystitis': {'urgency': 3, 'golden_hour': 1440},
    'prostatitis': {'urgency': 3, 'golden_hour': 1440},
    'epididymitis': {'urgency': 3, 'golden_hour': 1440},
    'pelvic inflammatory disease': {'urgency': 3, 'golden_hour': 720},
    'cervicitis': {'urgency': 3, 'golden_hour': 1440},
    'cellulitis or abscess of mouth': {'urgency': 3, 'golden_hour': 720},
    'tooth abscess': {'urgency': 3, 'golden_hour': 720},
    'impetigo': {'urgency': 3, 'golden_hour': 1440},
    'pyogenic skin infection': {'urgency': 3, 'golden_hour': 1440},
    'perirectal infection': {'urgency': 3, 'golden_hour': 720},
    'pilonidal cyst': {'urgency': 3, 'golden_hour': 1440},
    'spontaneous abortion': {'urgency': 3, 'golden_hour': 720},
    'missed abortion': {'urgency': 3, 'golden_hour': 1440},
    'induced abortion': {'urgency': 3, 'golden_hour': 720},
    'threatened pregnancy': {'urgency': 3, 'golden_hour': 720},
    'problem during pregnancy': {'urgency': 3, 'golden_hour': 720},
    'hyperemesis gravidarum': {'urgency': 3, 'golden_hour': 720},
    'angina': {'urgency': 3, 'golden_hour': 480},
    'ischemic heart disease': {'urgency': 3, 'golden_hour': 720},
    'arrhythmia': {'urgency': 3, 'golden_hour': 720},
    'premature ventricular contractions (pvcs)': {'urgency': 3, 'golden_hour': 1440},
    'premature atrial contractions (pacs)': {'urgency': 3, 'golden_hour': 1440},
    'fracture of the rib': {'urgency': 3, 'golden_hour': 720},
    'fracture of the arm': {'urgency': 3, 'golden_hour': 720},
    'fracture of the leg': {'urgency': 3, 'golden_hour': 720},
    'fracture of the hand': {'urgency': 3, 'golden_hour': 720},
    'fracture of the shoulder': {'urgency': 3, 'golden_hour': 720},
    'fracture of the facial bones': {'urgency': 3, 'golden_hour': 720},
    'fracture of the patella': {'urgency': 3, 'golden_hour': 720},
    'fracture of the jaw': {'urgency': 3, 'golden_hour': 720},
    'sprain or strain': {'urgency': 3, 'golden_hour': 1440},
    'injury to the arm': {'urgency': 3, 'golden_hour': 720},
    'injury to the leg': {'urgency': 3, 'golden_hour': 720},
    'injury to the trunk': {'urgency': 3, 'golden_hour': 720},
    'injury to the shoulder': {'urgency': 3, 'golden_hour': 720},
    'injury to the hand': {'urgency': 3, 'golden_hour': 720},
    'injury of the ankle': {'urgency': 3, 'golden_hour': 720},
    'injury to the knee': {'urgency': 3, 'golden_hour': 720},
    'injury to the face': {'urgency': 3, 'golden_hour': 720},
    'broken tooth': {'urgency': 3, 'golden_hour': 720},
    'open wound of the mouth': {'urgency': 3, 'golden_hour': 720},
    'gout': {'urgency': 3, 'golden_hour': 1440},
    'acute stress reaction': {'urgency': 3, 'golden_hour': 1440},
    'panic attack': {'urgency': 3, 'golden_hour': 720},
    'psychotic disorder': {'urgency': 3, 'golden_hour': 720},
    'drug abuse (opioids)': {'urgency': 3, 'golden_hour': 720},
    'drug abuse (cocaine)': {'urgency': 3, 'golden_hour': 720},
    'drug abuse (methamphetamine)': {'urgency': 3, 'golden_hour': 720},
    'drug abuse (barbiturates)': {'urgency': 3, 'golden_hour': 720},
    'drug abuse': {'urgency': 3, 'golden_hour': 720},
    'envenomation from spider or animal bite': {'urgency': 3, 'golden_hour': 240},
    'food allergy': {'urgency': 3, 'golden_hour': 240},
    'allergy': {'urgency': 3, 'golden_hour': 720},
    'drug reaction': {'urgency': 3, 'golden_hour': 720},
    'urinary tract obstruction': {'urgency': 3, 'golden_hour': 720},
    'hydronephrosis': {'urgency': 3, 'golden_hour': 720},
    'bladder obstruction': {'urgency': 3, 'golden_hour': 720},
    'urethral stricture': {'urgency': 3, 'golden_hour': 1440},
    'shingles (herpes zoster)': {'urgency': 3, 'golden_hour': 1440},
    'herpes zoster ophthalmicus': {'urgency': 3, 'golden_hour': 720},
    'scarlet fever': {'urgency': 3, 'golden_hour': 720},
    'mononucleosis': {'urgency': 3, 'golden_hour': 1440},
    'lyme disease': {'urgency': 3, 'golden_hour': 1440},
    'endometriosis': {'urgency': 3, 'golden_hour': 1440},
    'vasculitis': {'urgency': 3, 'golden_hour': 720},
    'thrombophlebitis': {'urgency': 3, 'golden_hour': 720},
    'hematoma': {'urgency': 3, 'golden_hour': 720},
    'subconjunctival hemorrhage': {'urgency': 3, 'golden_hour': 1440},
    'heat exhaustion': {'urgency': 3, 'golden_hour': 240},
    'orthostatic hypotension': {'urgency': 3, 'golden_hour': 720},
    'chronic pancreatitis': {'urgency': 3, 'golden_hour': 1440},
    'cirrhosis': {'urgency': 3, 'golden_hour': 1440},
    'alcoholic liver disease': {'urgency': 3, 'golden_hour': 1440},
    'hepatitis due to a toxin': {'urgency': 3, 'golden_hour': 720},
    
    # ============================================================
    # LEVEL 2 - STANDARD (2-3 days)
    # ============================================================
    'common cold': {'urgency': 2, 'golden_hour': 4320},
    'flu': {'urgency': 2, 'golden_hour': 2880},
    'strep throat': {'urgency': 2, 'golden_hour': 2880},
    'tonsillitis': {'urgency': 2, 'golden_hour': 2880},
    'laryngitis': {'urgency': 2, 'golden_hour': 4320},
    'otitis media': {'urgency': 2, 'golden_hour': 2880},
    'otitis externa (swimmer\'s ear)': {'urgency': 2, 'golden_hour': 2880},
    'chronic otitis media': {'urgency': 2, 'golden_hour': 4320},
    'sinusitis': {'urgency': 2, 'golden_hour': 4320},
    'chronic sinusitis': {'urgency': 2, 'golden_hour': None},
    'bronchitis': {'urgency': 2, 'golden_hour': 2880},
    'gastritis': {'urgency': 2, 'golden_hour': 2880},
    'gastroduodenal ulcer': {'urgency': 2, 'golden_hour': 2880},
    'gastroesophageal reflux disease (gerd)': {'urgency': 2, 'golden_hour': None},
    'esophagitis': {'urgency': 2, 'golden_hour': 2880},
    'infectious gastroenteritis': {'urgency': 2, 'golden_hour': 2880},
    'noninfectious gastroenteritis': {'urgency': 2, 'golden_hour': 2880},
    'indigestion': {'urgency': 2, 'golden_hour': 4320},
    'diverticulosis': {'urgency': 2, 'golden_hour': None},
    'hemorrhoids': {'urgency': 2, 'golden_hour': None},
    'anal fissure': {'urgency': 2, 'golden_hour': None},
    'constipation': {'urgency': 2, 'golden_hour': 2880},
    'chronic constipation': {'urgency': 2, 'golden_hour': None},
    'irritable bowel syndrome': {'urgency': 2, 'golden_hour': None},
    'conjunctivitis': {'urgency': 2, 'golden_hour': 2880},
    'conjunctivitis due to allergy': {'urgency': 2, 'golden_hour': 2880},
    'conjunctivitis due to virus': {'urgency': 2, 'golden_hour': 2880},
    'conjunctivitis due to bacteria': {'urgency': 2, 'golden_hour': 2880},
    'stye': {'urgency': 2, 'golden_hour': 2880},
    'chalazion': {'urgency': 2, 'golden_hour': None},
    'blepharitis': {'urgency': 2, 'golden_hour': None},
    'dry eye of unknown cause': {'urgency': 2, 'golden_hour': None},
    'seasonal allergies (hay fever)': {'urgency': 2, 'golden_hour': None},
    'contact dermatitis': {'urgency': 2, 'golden_hour': 2880},
    'eczema': {'urgency': 2, 'golden_hour': None},
    'psoriasis': {'urgency': 2, 'golden_hour': None},
    'acne': {'urgency': 2, 'golden_hour': None},
    'rosacea': {'urgency': 2, 'golden_hour': None},
    'fungal infection of the skin': {'urgency': 2, 'golden_hour': None},
    'fungal infection of the hair': {'urgency': 2, 'golden_hour': None},
    'athlete\'s foot': {'urgency': 2, 'golden_hour': None},
    'onychomycosis': {'urgency': 2, 'golden_hour': None},
    'viral warts': {'urgency': 2, 'golden_hour': None},
    'molluscum contagiosum': {'urgency': 2, 'golden_hour': None},
    'insect bite': {'urgency': 2, 'golden_hour': 2880},
    'scabies': {'urgency': 2, 'golden_hour': 2880},
    'lice': {'urgency': 2, 'golden_hour': 2880},
    'pinworm infection': {'urgency': 2, 'golden_hour': 2880},
    'chickenpox': {'urgency': 2, 'golden_hour': 2880},
    'genital herpes': {'urgency': 2, 'golden_hour': 2880},
    'cold sore': {'urgency': 2, 'golden_hour': 2880},
    'oral thrush (yeast infection)': {'urgency': 2, 'golden_hour': 2880},
    'vaginal yeast infection': {'urgency': 2, 'golden_hour': 2880},
    'yeast infection': {'urgency': 2, 'golden_hour': 2880},
    'trichomonas infection': {'urgency': 2, 'golden_hour': 2880},
    'chlamydia': {'urgency': 2, 'golden_hour': 2880},
    'gonorrhea': {'urgency': 2, 'golden_hour': 2880},
    'urethritis': {'urgency': 2, 'golden_hour': 2880},
    'vaginitis': {'urgency': 2, 'golden_hour': 2880},
    'balanitis': {'urgency': 2, 'golden_hour': 2880},
    'bursitis': {'urgency': 2, 'golden_hour': None},
    'tendinitis': {'urgency': 2, 'golden_hour': None},
    'muscle spasm': {'urgency': 2, 'golden_hour': 2880},
    'back pain': {'urgency': 2, 'golden_hour': None},
    'chronic back pain': {'urgency': 2, 'golden_hour': None},
    'lumbago': {'urgency': 2, 'golden_hour': None},
    'sciatica': {'urgency': 2, 'golden_hour': None},
    'neck pain': {'urgency': 2, 'golden_hour': None},
    'pain disorder affecting the neck': {'urgency': 2, 'golden_hour': None},
    'tension headache': {'urgency': 2, 'golden_hour': 2880},
    'migraine': {'urgency': 2, 'golden_hour': 1440},
    'headache after lumbar puncture': {'urgency': 2, 'golden_hour': 2880},
    'dental caries': {'urgency': 2, 'golden_hour': None},
    'gum disease': {'urgency': 2, 'golden_hour': None},
    'tooth disorder': {'urgency': 2, 'golden_hour': None},
    'anxiety': {'urgency': 2, 'golden_hour': None},
    'depression': {'urgency': 2, 'golden_hour': None},
    'insomnia': {'urgency': 2, 'golden_hour': None},
    'primary insomnia': {'urgency': 2, 'golden_hour': None},
    'panic disorder': {'urgency': 2, 'golden_hour': None},
    'postpartum depression': {'urgency': 2, 'golden_hour': 2880},
    'dysthymic disorder': {'urgency': 2, 'golden_hour': None},
    'rotator cuff injury': {'urgency': 2, 'golden_hour': None},
    'knee ligament or meniscus tear': {'urgency': 2, 'golden_hour': None},
    'carpal tunnel syndrome': {'urgency': 2, 'golden_hour': None},
    'plantar fasciitis': {'urgency': 2, 'golden_hour': None},
    'lateral epicondylitis (tennis elbow)': {'urgency': 2, 'golden_hour': None},
    'de quervain disease': {'urgency': 2, 'golden_hour': None},
    'trigger finger (finger disorder)': {'urgency': 2, 'golden_hour': None},
    'benign prostatic hyperplasia (bph)': {'urgency': 2, 'golden_hour': None},
    'urge incontinence': {'urgency': 2, 'golden_hour': None},
    'stress incontinence': {'urgency': 2, 'golden_hour': None},
    'overflow incontinence': {'urgency': 2, 'golden_hour': None},
    'ovarian cyst': {'urgency': 2, 'golden_hour': 2880},
    'uterine fibroids': {'urgency': 2, 'golden_hour': None},
    'idiopathic painful menstruation': {'urgency': 2, 'golden_hour': None},
    'idiopathic excessive menstruation': {'urgency': 2, 'golden_hour': None},
    'idiopathic absence of menstruation': {'urgency': 2, 'golden_hour': None},
    'idiopathic irregular menstrual cycle': {'urgency': 2, 'golden_hour': None},
    'idiopathic infrequent menstruation': {'urgency': 2, 'golden_hour': None},
    'idiopathic nonmenstrual bleeding': {'urgency': 2, 'golden_hour': None},
    'premenstrual tension syndrome': {'urgency': 2, 'golden_hour': None},
    'benign vaginal discharge (leukorrhea)': {'urgency': 2, 'golden_hour': None},
    'atrophic vaginitis': {'urgency': 2, 'golden_hour': None},
    'vulvodynia': {'urgency': 2, 'golden_hour': None},
    'vaginal cyst': {'urgency': 2, 'golden_hour': None},
    'vulvar disorder': {'urgency': 2, 'golden_hour': None},
    'erectile dysfunction': {'urgency': 2, 'golden_hour': None},
    'varicocele of the testicles': {'urgency': 2, 'golden_hour': None},
    'hydrocele of the testicle': {'urgency': 2, 'golden_hour': None},
    'spermatocele': {'urgency': 2, 'golden_hour': None},
    'phimosis': {'urgency': 2, 'golden_hour': None},
    'testicular disorder': {'urgency': 2, 'golden_hour': 2880},
    'ear wax impaction': {'urgency': 2, 'golden_hour': None},
    'eustachian tube dysfunction (ear disorder)': {'urgency': 2, 'golden_hour': None},
    'sensorineural hearing loss': {'urgency': 2, 'golden_hour': None},
    'conductive hearing loss': {'urgency': 2, 'golden_hour': None},
    'tinnitus of unknown cause': {'urgency': 2, 'golden_hour': None},
    'labyrinthitis': {'urgency': 2, 'golden_hour': 2880},
    'benign paroxysmal positional vertical (bppv)': {'urgency': 2, 'golden_hour': None},
    'meniere disease': {'urgency': 2, 'golden_hour': None},
    'glaucoma': {'urgency': 2, 'golden_hour': None},
    'chronic glaucoma': {'urgency': 2, 'golden_hour': None},
    'cataract': {'urgency': 2, 'golden_hour': None},
    'macular degeneration': {'urgency': 2, 'golden_hour': None},
    'diabetic retinopathy': {'urgency': 2, 'golden_hour': None},
    'pterygium': {'urgency': 2, 'golden_hour': None},
    'myopia': {'urgency': 2, 'golden_hour': None},
    'hyperopia': {'urgency': 2, 'golden_hour': None},
    'astigmatism': {'urgency': 2, 'golden_hour': None},
    'presbyopia': {'urgency': 2, 'golden_hour': None},
    'corneal disorder': {'urgency': 2, 'golden_hour': None},
    'eye alignment disorder': {'urgency': 2, 'golden_hour': None},
    'vitreous degeneration': {'urgency': 2, 'golden_hour': None},
    'retinopathy due to high blood pressure': {'urgency': 2, 'golden_hour': None},
    'stenosis of the tear duct': {'urgency': 2, 'golden_hour': None},
    'chorioretinitis': {'urgency': 2, 'golden_hour': 2880},
    'persistent vomiting of unknown cause': {'urgency': 2, 'golden_hour': 2880},
    'iron deficiency anemia': {'urgency': 2, 'golden_hour': None},
    'anemia': {'urgency': 2, 'golden_hour': None},
    'anemia due to chronic kidney disease': {'urgency': 2, 'golden_hour': None},
    'sickle cell anemia': {'urgency': 2, 'golden_hour': None},
    'vitamin b12 deficiency': {'urgency': 2, 'golden_hour': None},
    'hypothyroidism': {'urgency': 2, 'golden_hour': None},
    'graves disease': {'urgency': 2, 'golden_hour': None},
    'goiter': {'urgency': 2, 'golden_hour': None},
    'toxic multinodular goiter': {'urgency': 2, 'golden_hour': None},
    'thyroid nodule': {'urgency': 2, 'golden_hour': None},
    'polycystic ovarian syndrome (pcos)': {'urgency': 2, 'golden_hour': None},
    'bell palsy': {'urgency': 2, 'golden_hour': 2880},
    'trigeminal neuralgia': {'urgency': 2, 'golden_hour': None},
    'neuralgia': {'urgency': 2, 'golden_hour': None},
    'restless leg syndrome': {'urgency': 2, 'golden_hour': None},
    'essential tremor': {'urgency': 2, 'golden_hour': None},
    'torticollis': {'urgency': 2, 'golden_hour': 2880},
    'abdominal hernia': {'urgency': 2, 'golden_hour': None},
    'inguinal hernia': {'urgency': 2, 'golden_hour': None},
    'hiatal hernia': {'urgency': 2, 'golden_hour': None},
    'ulcerative colitis': {'urgency': 2, 'golden_hour': None},
    'crohn disease': {'urgency': 2, 'golden_hour': None},
    'celiac disease': {'urgency': 2, 'golden_hour': None},
    'lactose intolerance': {'urgency': 2, 'golden_hour': None},
    'intestinal malabsorption': {'urgency': 2, 'golden_hour': None},
    'gastroparesis': {'urgency': 2, 'golden_hour': None},
    'stricture of the esophagus': {'urgency': 2, 'golden_hour': None},
    'achalasia': {'urgency': 2, 'golden_hour': None},
    'colonic polyp': {'urgency': 2, 'golden_hour': None},
    'nasal polyp': {'urgency': 2, 'golden_hour': None},
    'skin polyp': {'urgency': 2, 'golden_hour': None},
    'vocal cord polyp': {'urgency': 2, 'golden_hour': None},
    'deviated nasal septum': {'urgency': 2, 'golden_hour': None},
    'tonsillar hypertrophy': {'urgency': 2, 'golden_hour': None},
    'obstructive sleep apnea (osa)': {'urgency': 2, 'golden_hour': None},
    'nose disorder': {'urgency': 2, 'golden_hour': None},
    'abscess of nose': {'urgency': 2, 'golden_hour': 2880},
    'ingrown toe nail': {'urgency': 2, 'golden_hour': None},
    'paronychia': {'urgency': 2, 'golden_hour': 2880},
    
    # ============================================================
    # LEVEL 1 - ELECTIVE (Chronic/Scheduled)
    # ============================================================
    'osteoarthritis': {'urgency': 1, 'golden_hour': None},
    'arthritis of the hip': {'urgency': 1, 'golden_hour': None},
    'rheumatoid arthritis': {'urgency': 1, 'golden_hour': None},
    'ankylosing spondylitis': {'urgency': 1, 'golden_hour': None},
    'spondylosis': {'urgency': 1, 'golden_hour': None},
    'spondylitis': {'urgency': 1, 'golden_hour': None},
    'spondylolisthesis': {'urgency': 1, 'golden_hour': None},
    'spinal stenosis': {'urgency': 1, 'golden_hour': None},
    'herniated disk': {'urgency': 1, 'golden_hour': None},
    'degenerative disc disease': {'urgency': 1, 'golden_hour': None},
    'osteoporosis': {'urgency': 1, 'golden_hour': None},
    'scoliosis': {'urgency': 1, 'golden_hour': None},
    'osteochondroma': {'urgency': 1, 'golden_hour': None},
    'osteochondrosis': {'urgency': 1, 'golden_hour': None},
    'bone disorder': {'urgency': 1, 'golden_hour': None},
    'fibromyalgia': {'urgency': 1, 'golden_hour': None},
    'chronic pain disorder': {'urgency': 1, 'golden_hour': None},
    'complex regional pain syndrome': {'urgency': 1, 'golden_hour': None},
    'chronic knee pain': {'urgency': 1, 'golden_hour': None},
    'adhesive capsulitis of the shoulder': {'urgency': 1, 'golden_hour': None},
    'chondromalacia of the patella': {'urgency': 1, 'golden_hour': None},
    'thoracic outlet syndrome': {'urgency': 1, 'golden_hour': None},
    'nerve impingement near the shoulder': {'urgency': 1, 'golden_hour': None},
    'brachial neuritis': {'urgency': 1, 'golden_hour': None},
    'peripheral nerve disorder': {'urgency': 1, 'golden_hour': None},
    'diabetic peripheral neuropathy': {'urgency': 1, 'golden_hour': None},
    'mononeuritis': {'urgency': 1, 'golden_hour': None},
    'cranial nerve palsy': {'urgency': 1, 'golden_hour': None},
    'varicose veins': {'urgency': 1, 'golden_hour': None},
    'venous insufficiency': {'urgency': 1, 'golden_hour': None},
    'lymphedema': {'urgency': 1, 'golden_hour': None},
    'peripheral arterial disease': {'urgency': 1, 'golden_hour': None},
    'coronary atherosclerosis': {'urgency': 1, 'golden_hour': None},
    'chronic obstructive pulmonary disease (copd)': {'urgency': 1, 'golden_hour': None},
    'interstitial lung disease': {'urgency': 1, 'golden_hour': None},
    'pulmonary fibrosis': {'urgency': 1, 'golden_hour': None},
    'pulmonary eosinophilia': {'urgency': 1, 'golden_hour': None},
    'sarcoidosis': {'urgency': 1, 'golden_hour': None},
    'liver disease': {'urgency': 1, 'golden_hour': None},
    'nonalcoholic liver disease (nash)': {'urgency': 1, 'golden_hour': None},
    'polycystic kidney disease': {'urgency': 1, 'golden_hour': None},
    'benign kidney cyst': {'urgency': 1, 'golden_hour': None},
    'intestinal disease': {'urgency': 1, 'golden_hour': None},
    'atonic bladder': {'urgency': 1, 'golden_hour': None},
    'bladder disorder': {'urgency': 1, 'golden_hour': None},
    'urethral disorder': {'urgency': 1, 'golden_hour': None},
    'pelvic organ prolapse': {'urgency': 1, 'golden_hour': None},
    'hypertensive heart disease': {'urgency': 1, 'golden_hour': None},
    'mitral valve disease': {'urgency': 1, 'golden_hour': None},
    'aortic valve disease': {'urgency': 1, 'golden_hour': None},
    'chronic rheumatic fever': {'urgency': 1, 'golden_hour': None},
    'multiple sclerosis': {'urgency': 1, 'golden_hour': None},
    'parkinson disease': {'urgency': 1, 'golden_hour': None},
    'epilepsy': {'urgency': 1, 'golden_hour': None},
    'dementia': {'urgency': 1, 'golden_hour': None},
    'alzheimer disease': {'urgency': 1, 'golden_hour': None},
    'lewy body dementia': {'urgency': 1, 'golden_hour': None},
    'cerebral palsy': {'urgency': 1, 'golden_hour': None},
    'hemiplegia': {'urgency': 1, 'golden_hour': None},
    'myasthenia gravis': {'urgency': 1, 'golden_hour': None},
    'amyotrophic lateral sclerosis (als)': {'urgency': 1, 'golden_hour': None},
    'hydrocephalus': {'urgency': 1, 'golden_hour': None},
    'spina bifida': {'urgency': 1, 'golden_hour': None},
    'autonomic nervous system disorder': {'urgency': 1, 'golden_hour': None},
    'narcolepsy': {'urgency': 1, 'golden_hour': None},
    'systemic lupus erythematosis (sle)': {'urgency': 1, 'golden_hour': None},
    'scleroderma': {'urgency': 1, 'golden_hour': None},
    'sjogren syndrome': {'urgency': 1, 'golden_hour': None},
    'polymyalgia rheumatica': {'urgency': 1, 'golden_hour': None},
    'myositis': {'urgency': 1, 'golden_hour': None},
    'schizophrenia': {'urgency': 1, 'golden_hour': None},
    'bipolar disorder': {'urgency': 1, 'golden_hour': None},
    'personality disorder': {'urgency': 1, 'golden_hour': None},
    'obsessive compulsive disorder (ocd)': {'urgency': 1, 'golden_hour': None},
    'social phobia': {'urgency': 1, 'golden_hour': None},
    'post-traumatic stress disorder (ptsd)': {'urgency': 1, 'golden_hour': None},
    'eating disorder': {'urgency': 1, 'golden_hour': None},
    'impulse control disorder': {'urgency': 1, 'golden_hour': None},
    'oppositional disorder': {'urgency': 1, 'golden_hour': None},
    'conduct disorder': {'urgency': 1, 'golden_hour': None},
    'attention deficit hyperactivity disorder (adhd)': {'urgency': 1, 'golden_hour': None},
    'autism': {'urgency': 1, 'golden_hour': None},
    'asperger syndrome': {'urgency': 1, 'golden_hour': None},
    'developmental disability': {'urgency': 1, 'golden_hour': None},
    'down syndrome': {'urgency': 1, 'golden_hour': None},
    'neurosis': {'urgency': 1, 'golden_hour': None},
    'adjustment reaction': {'urgency': 1, 'golden_hour': None},
    'somatization disorder': {'urgency': 1, 'golden_hour': None},
    'dissociative disorder': {'urgency': 1, 'golden_hour': None},
    'psychosexual disorder': {'urgency': 1, 'golden_hour': None},
    'vaginismus': {'urgency': 1, 'golden_hour': None},
    'tic (movement) disorder': {'urgency': 1, 'golden_hour': None},
    'substance-related mental disorder': {'urgency': 1, 'golden_hour': None},
    'alcohol abuse': {'urgency': 1, 'golden_hour': None},
    'marijuana abuse': {'urgency': 1, 'golden_hour': None},
    'smoking or tobacco addiction': {'urgency': 1, 'golden_hour': None},
    'extrapyramidal effect of drugs': {'urgency': 1, 'golden_hour': None},
    'hormone disorder': {'urgency': 1, 'golden_hour': None},
    'menopause': {'urgency': 1, 'golden_hour': None},
    'gynecomastia': {'urgency': 1, 'golden_hour': None},
    'white blood cell disease': {'urgency': 1, 'golden_hour': None},
    'alopecia': {'urgency': 1, 'golden_hour': None},
    'hidradenitis suppurativa': {'urgency': 1, 'golden_hour': None},
    'sebaceous cyst': {'urgency': 1, 'golden_hour': None},
    'lipoma': {'urgency': 1, 'golden_hour': None},
    'hemangioma': {'urgency': 1, 'golden_hour': None},
    'ganglion cyst': {'urgency': 1, 'golden_hour': None},
    'fibroadenoma': {'urgency': 1, 'golden_hour': None},
    'seborrheic dermatitis': {'urgency': 1, 'golden_hour': None},
    'seborrheic keratosis': {'urgency': 1, 'golden_hour': None},
    'actinic keratosis': {'urgency': 1, 'golden_hour': None},
    'skin disorder': {'urgency': 1, 'golden_hour': None},
    'skin pigmentation disorder': {'urgency': 1, 'golden_hour': None},
    'atrophic skin condition': {'urgency': 1, 'golden_hour': None},
    'lichen simplex': {'urgency': 1, 'golden_hour': None},
    'pityriasis rosea': {'urgency': 1, 'golden_hour': None},
    'intertrigo (skin condition)': {'urgency': 1, 'golden_hour': None},
    'dyshidrosis': {'urgency': 1, 'golden_hour': None},
    'scar': {'urgency': 1, 'golden_hour': None},
    'callus': {'urgency': 1, 'golden_hour': None},
    'itching of unknown cause': {'urgency': 1, 'golden_hour': None},
    'dermatitis due to sun exposure': {'urgency': 1, 'golden_hour': None},
    'diaper rash': {'urgency': 1, 'golden_hour': None},
    'teething syndrome': {'urgency': 1, 'golden_hour': None},
    'aphthous ulcer': {'urgency': 1, 'golden_hour': None},
    'oral mucosal lesion': {'urgency': 1, 'golden_hour': None},
    'mucositis': {'urgency': 1, 'golden_hour': None},
    'jaw disorder': {'urgency': 1, 'golden_hour': None},
    'temporomandibular joint disorder': {'urgency': 1, 'golden_hour': None},
    'rectal disorder': {'urgency': 1, 'golden_hour': None},
    'salivary gland disorder': {'urgency': 1, 'golden_hour': None},
    'sialoadenitis': {'urgency': 1, 'golden_hour': None},
    'tietze syndrome': {'urgency': 1, 'golden_hour': None},
    'joint effusion': {'urgency': 1, 'golden_hour': None},
    'ear drum damage': {'urgency': 1, 'golden_hour': None},
    'presbyacusis': {'urgency': 1, 'golden_hour': None},
    'temporary or benign blood in urine': {'urgency': 1, 'golden_hour': None},
    'protein deficiency': {'urgency': 1, 'golden_hour': None},
    'parasitic disease': {'urgency': 1, 'golden_hour': None},
    'sinus bradycardia': {'urgency': 1, 'golden_hour': None},
    'mittelschmerz': {'urgency': 1, 'golden_hour': None},
    'breast infection (mastitis)': {'urgency': 2, 'golden_hour': 2880},
    'female genitalia infection': {'urgency': 2, 'golden_hour': 2880},
    'male genitalia infection': {'urgency': 2, 'golden_hour': 2880},
    'postoperative infection': {'urgency': 2, 'golden_hour': 1440},
    'viral exanthem': {'urgency': 1, 'golden_hour': None},
    'herpangina': {'urgency': 1, 'golden_hour': None},
    'pain after an operation': {'urgency': 1, 'golden_hour': None},
    
    # CANCERS - Variable urgency based on type
    'skin cancer': {'urgency': 2, 'golden_hour': None},
    'melanoma': {'urgency': 3, 'golden_hour': None},
    'brain cancer': {'urgency': 3, 'golden_hour': None},
    'lung cancer': {'urgency': 3, 'golden_hour': None},
    'stomach cancer': {'urgency': 3, 'golden_hour': None},
    'pancreatic cancer': {'urgency': 3, 'golden_hour': None},
    'esophageal cancer': {'urgency': 3, 'golden_hour': None},
    'bladder cancer': {'urgency': 2, 'golden_hour': None},
    'kidney cancer': {'urgency': 2, 'golden_hour': None},
    'prostate cancer': {'urgency': 2, 'golden_hour': None},
    'cervical cancer': {'urgency': 2, 'golden_hour': None},
    'endometrial cancer': {'urgency': 2, 'golden_hour': None},
    'bone cancer': {'urgency': 3, 'golden_hour': None},
    'soft tissue sarcoma': {'urgency': 3, 'golden_hour': None},
    'head and neck cancer': {'urgency': 3, 'golden_hour': None},
    'lymphoma': {'urgency': 3, 'golden_hour': None},
    'multiple myeloma': {'urgency': 3, 'golden_hour': None},
    'lymphadenitis': {'urgency': 2, 'golden_hour': 2880},
}

# Default urgency for unmapped diseases
DEFAULT_URGENCY = 2


def get_urgency(disease_name):
    """Get urgency level for a disease"""
    disease_lower = disease_name.lower().strip()
    if disease_lower in URGENCY_MAPPING:
        return URGENCY_MAPPING[disease_lower]['urgency']
    return DEFAULT_URGENCY


def get_golden_hour(disease_name):
    """Get golden hour minutes for a disease"""
    disease_lower = disease_name.lower().strip()
    if disease_lower in URGENCY_MAPPING:
        return URGENCY_MAPPING[disease_lower].get('golden_hour')
    return None


# Summary statistics
if __name__ == '__main__':
    from collections import Counter
    urgencies = [v['urgency'] for v in URGENCY_MAPPING.values()]
    counts = Counter(urgencies)
    print("Urgency Distribution:")
    for level in sorted(counts.keys(), reverse=True):
        print(f"  Level {level}: {counts[level]} diseases")
    print(f"\nTotal mapped: {len(URGENCY_MAPPING)} diseases")
