import { Patient } from './types';

export const COLORS = {
    primary: '#3B82F6',
    secondary: '#10B981',
    danger: '#EF4444',
    warning: '#F59E0B',
    navy: '#0A0F1C',
    gray: '#64748B',
};

export const MOCK_PATIENTS: Patient[] = [
    {
        id: '8492',
        name: 'John Doe',
        age: 64,
        gender: 'Male',
        systolic_bp: 142,
        diastolic_bp: 91,
        glucose: 110,
        bmi: 28.4,
        cholesterol: 215,
        heart_rate: 82,
        steps: 4200,
        smoking: true,
        alcohol: false,
        medications: ['Lisinopril', 'Metformin'],
        history_heart_disease: true,
        history_stroke: false,
        history_diabetes: true,
        history_high_chol: true,
        admitted_at: '2023-10-24T08:30:00Z',
        attending: 'Dr. Sarah Smith',
        status: 'Critical',
    },
    {
        id: '1205',
        name: 'Jane Miller',
        age: 45,
        gender: 'Female',
        systolic_bp: 118,
        diastolic_bp: 78,
        glucose: 92,
        bmi: 22.1,
        cholesterol: 180,
        heart_rate: 68,
        steps: 12000,
        smoking: false,
        alcohol: true,
        medications: [],
        history_heart_disease: false,
        history_stroke: false,
        history_diabetes: false,
        history_high_chol: false,
        admitted_at: '2023-10-25T14:15:00Z',
        attending: 'Dr. Robert Chen',
        status: 'Stable',
    },
    {
        id: '9931',
        name: 'Elias Thorne',
        age: 78,
        gender: 'Male',
        systolic_bp: 160,
        diastolic_bp: 95,
        glucose: 145,
        bmi: 31.2,
        cholesterol: 240,
        heart_rate: 94,
        steps: 1500,
        smoking: false,
        alcohol: false,
        medications: ['Amlodipine', 'Simvastatin'],
        history_heart_disease: true,
        history_stroke: true,
        history_diabetes: false,
        history_high_chol: true,
        admitted_at: '2023-10-25T10:00:00Z',
        attending: 'Dr. Sarah Smith',
        status: 'Observing',
    }
];
